version: '3.8'

services:
  ruckus-exporter:
    build:
      context: .
      dockerfile: Dockerfile
      # Multi-platform build configuration
      platforms:
        - linux/amd64
        - linux/arm64
    container_name: ruckus-ap-exporter
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      # Multiple APs (comma-separated)
      - RUCKUS_AP_HOSTS=192.168.1.100,192.168.1.101
      - SNMP_COMMUNITY=public
      - SNMP_PORT=161
      - METRICS_PORT=8000
      - SCRAPE_INTERVAL=30
    networks:
      - monitoring
    # No platform restriction - Docker will use native architecture

  # Optional: Include Prometheus for testing
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge